"""empty message

Revision ID: 320b8469930e
Revises: 153c01ed51ff
Create Date: 2020-09-30 16:03:57.497706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320b8469930e'
down_revision = '153c01ed51ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    op.drop_column('users', 'accept_policy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_policy', sa.BOOLEAN(), nullable=True))
    op.create_table('global_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('about_text', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
